### ISSUE TITLE
Release with VS2015 support

### ISSUE THREAD

**Issue by neusdan** [vslavik/bakefile#68]
Hi,

i wan't to use bakefile to generate VS2015 project files. Unfortunately this feature is not released yet. I've tried to build a new Windows executable from source but get errors `Import Error: no module named plugins`.

Maybe you could make a new release or explain how to fix that error?

Thanks.

**Comment by vadz** [comment]
I have more changes in progress and I'd prefer to finish them before making the next release.

In the meanwhile, the simplest way to use the latest version is to install Python (2.7) and use it to run `src/bkl/tool.py`.

**Comment by neusdan** [comment]
I just tried to run `tool.py` directly with Python 2.7.11. But then i get this error:
```
C:\Coding\bakefile\src>python tool.py xyz.bkl
Traceback (most recent call last):
  File "tool.py", line 143, in <module>
    from bkl.interpreter import Interpreter
  File "C:\Coding\bakefile\src\bkl\interpreter\__init__.py", line 32, in <module>
    import bkl.parser
  File "C:\Coding\bakefile\src\bkl\parser\__init__.py", line 38, in <module>
    import ast
  File "C:\Coding\bakefile\src\bkl\parser\ast.py", line 27, in <module>
    import BakefileParser
ImportError: No module named BakefileParser
```

I'm not familar with Python but i've read that i can set the module search Path like this:

```
C:\Coding\bakefile\src>set PYTHONPATH=C:\Coding\bakefile\src\bkl
```
Unfortunately this doesn't help really:
```
C:\Coding\bakefile\src>python tool.py xyz.bkl
Traceback (most recent call last):
  File "tool.py", line 142, in <module>
    import bkl.error
  File "C:\Coding\bakefile\src\bkl\__init__.py", line 25, in <module>
    import plugins
  File "C:\Coding\bakefile\src\bkl\plugins\__init__.py", line 89, in <module>
    from . import *
  File "C:\Coding\bakefile\src\bkl\plugins\external.py", line 32, in <module>
    from bkl.plugins.vsbase import VSProjectBase, PROJECT_KIND_NET
  File "C:\Coding\bakefile\src\bkl\plugins\vsbase.py", line 31, in <module>
    from xml.sax.saxutils import escape, quoteattr
  File "C:\Python27\lib\xml\sax\saxutils.py", line 106, in <module>
    class _UnbufferedTextIOWrapper(io.TextIOWrapper):
AttributeError: 'module' object has no attribute 'TextIOWrapper'
```

If this is too hard to explain, thats ok. I will wait for the release.

**Comment by vslavik** [comment]
> But then i get this error:

Well, you also have to read the README file and follow the instructions in there to build. For building the distrib binaries, there’s distrib/README.
