### ISSUE TITLE
Bakefile trunk does not run

### ISSUE THREAD

**Issue by briangorman** [vslavik/bakefile#81]
>./bkl hello.bkl 
Traceback (most recent call last):
  File "./bkl", line 143, in <module>
    from bkl.interpreter import Interpreter
  File "/users/gormanbr/Downloads/bakefile-master/src/bkl/interpreter/__init__.py", line 32, in <module>
    import bkl.parser
  File "/users/gormanbr/Downloads/bakefile-master/src/bkl/parser/__init__.py", line 38, in <module>
    import ast
  File "/users/gormanbr/Downloads/bakefile-master/src/bkl/parser/ast.py", line 27, in <module>
    import BakefileParser
ImportError: No module named BakefileParser

OS: RHEL 6. The last "release" version does not have this problem.

**Comment by vslavik** [comment]
If you choose to use a git checkout, you *really* need to read & follow the [README](https://github.com/vslavik/bakefile/blob/master/README#L52).
