### ISSUE TITLE
Paths are not unicode safe

### ISSUE THREAD

**Issue by majo83** [vslavik/bakefile#96]
When given the following bakefile structure:
```
toolsets = gnu ;
corepath = ../../libraries/arduino-arcore/arcore/hardware/avr/cores/arcore;

library arcore_core {
    sources {
        $(corepath)/hooks.c   
        /* ... */
    }
}


program firmware_v1 {
    deps = arcore_core;
    sources {
        firmware_v1.cpp        
    }
}

```

corepath is relative to the used sourcedir, however the full path for corepath contained an umlaut (try e.g. töst). I got the following exception with it:

```

/usr/lib/python2.7/genericpath.py:79: UnicodeWarning: Unicode equal comparison failed to convert both arguments to Unicode - interpreting them as being unequal
  s1 = min(m)
Traceback (most recent call last):
  File "/usr/local/bin/bkl", line 160, in <module>
    intr.process_file(args[0])
  File "/usr/local/src/bakefile-1.2.5.1_beta/src/bkl/interpreter/__init__.py", line 112, in process_file
    self.process(parse_file(filename))
  File "/usr/local/src/bakefile-1.2.5.1_beta/src/bkl/interpreter/__init__.py", line 107, in process
    self.generate()
  File "/usr/local/src/bakefile-1.2.5.1_beta/src/bkl/interpreter/__init__.py", line 246, in generate
    self.generate_for_toolset(toolsets[-1], skip_making_copy=True)
  File "/usr/local/src/bakefile-1.2.5.1_beta/src/bkl/interpreter/__init__.py", line 258, in generate_for_toolset
    bkl.api.Toolset.get(toolset).generate(model)
  File "/usr/local/src/bakefile-1.2.5.1_beta/src/bkl/makefile.py", line 199, in generate
    self._gen_makefile(build_graphs, m)
  File "/usr/local/src/bakefile-1.2.5.1_beta/src/bkl/makefile.py", line 209, in _gen_makefile
    model=module)
  File "/usr/local/src/bakefile-1.2.5.1_beta/src/bkl/expr.py", line 862, in __init__
    to_top_srcdir = os.path.relpath(top_srcdir, start=outdir)
  File "/usr/lib/python2.7/posixpath.py", line 434, in relpath
    i = len(commonprefix([start_list, path_list]))
  File "/usr/lib/python2.7/genericpath.py", line 79, in commonprefix
    s1 = min(m)
UnicodeDecodeError: 'ascii' codec can't decode byte 0xc3 in position 6: ordinal not in range(128)

```

I used bakefile 1.2.5.1 on ubuntu with the following locale: 

```
$ locale 
LANG=en_US.UTF-8
LANGUAGE=en_US
LC_CTYPE="en_US.UTF-8"
LC_NUMERIC=de_AT.UTF-8
LC_TIME=de_AT.UTF-8
LC_COLLATE="en_US.UTF-8"
LC_MONETARY=de_AT.UTF-8
LC_MESSAGES="en_US.UTF-8"
LC_PAPER=de_AT.UTF-8
LC_NAME=de_AT.UTF-8
LC_ADDRESS=de_AT.UTF-8
LC_TELEPHONE=de_AT.UTF-8
LC_MEASUREMENT=de_AT.UTF-8
LC_IDENTIFICATION=de_AT.UTF-8
LC_ALL=
```

I appreciate your time. 

Regards,
majo83

**Comment by kirbyfan64** [comment]
What if you try it using Python 3?

**Comment by vadz** [comment]
I can easily reproduce the problem by applying this patch
```diff
diff --git a/tests/test_full.py b/tests/test_full.py
index 912be5ff..fc25795b 100644
--- a/tests/test_full.py
+++ b/tests/test_full.py
@@ -1,3 +1,4 @@
+# -*- coding: utf-8 -*-
 #
 #  This file is part of Bakefile (http://bakefile.org)
 #
@@ -96,3 +97,28 @@ expected model:
 """ % expected

     assert as_text == expected
+
+def test_unicode_filename():
+    """
+    This test checks that filenames relative to a directory containing
+    non-ASCII characters work correctly, see
+    https://github.com/vslavik/bakefile/issues/96
+    """
+    t = bkl.parser.parse("""
+toolsets = gnu;
+program progname {
+    sources { ../relpath.c }
+}
+""", "test.bkl")
+    i = InterpreterForTestSuite()
+
+    import shutil
+    import tempfile
+    cwd = os.getcwd()
+    tmpdir = tempfile.mkdtemp(prefix=u"Üñîçöḍè")
+    os.chdir(tmpdir)
+    try:
+        i.process(t)
+    finally:
+        os.chdir(cwd)
+        shutil.rmtree(tmpdir)
```
and running `pytest tests/test_full.py::test_unicode_filename`, but I don't know how to fix it because the error actually comes from the standard `os.path.relpath` function and it just seems broken for non-ASCII paths in Python 2.7.

I could well be missing something, of course...

**Comment by vslavik** [comment]
> it just seems broken for non-ASCII paths in Python 2.7.

I wouldn't say *broken* — it's "just" Unicode ignorant, as UNIX paths are as well. Presumably Python 3 has dealt with it somehow, but as long as we use Python 2, probably the only thing that can realistically be done about it is converting arguments passed to `os.path.*` functions from `unicode` to `str` (the bug comes from mixing ANSI and Unicode strings for the arguments).
